site_name: 'MDr docs'
site_description: 'Typecho 主题 MDr 的文档。'
site_author: 'FlyingSky'

# Repository
repo_name: 'FlyingSky-CN/MDr'
repo_url: 'https://github.com/FlyingSky-CN/MDr'
edit_uri: "https://github.com/FlyingSky-CN/MDr-docs/tree/source/docs"

# Copyright
copyright: 'Copyright &copy; 2019-2020 <a href="https://fsky7.com">FlyingSky</a>'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  include_search_page: false
  search_index_only: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/FlyingSky-CN/MDr'
    - type: 'globe'
      link: 'https://blog.fsky7.com/archives/60/'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true

nav:
  - 书写你的篇章: index.md
  - 在开始之前: before-start.md
  - 安装、更新及卸载: install.md
  - 隐私声明: privacy.md
  - 帮助我们: help-us.md